<?php

/**
 * EpisodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EpisodeTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object EpisodeTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Episode');
    }

    public function getEpisodesOfUser() {
        $user = sfContext::getInstance()->getUser()->getGuardUser();

        $q = Doctrine_Query::create()
                ->from('episode e');
        if (!$user->hasGroup('admin')) {
            $q = Doctrine_Query::create()
                    ->from('episode e')
                    ->innerJoin('e.Podcast p')
                    ->innerJoin('p.Owner o')
                    ->innerJoin('o.User s')
                    ->where('s.id = ?', $user->getId())
                    ->andWhere('e.podcast_id = p.id');
        }
        return $q;
    }

    public function getLastestEpisode() {
        $q = Doctrine_Query::create()
                        ->from('episode e')->orderBy('e.created_at');
        return $q->fetchOne();
    }

    public function getLastEpisodesOfPodcast($id) {

        $q = $this->createQuery('e')
                ->innerJoin('e.Podcast p')
                ->where("e.Podcast_id =  $id")
                ->orderBy('e.created_at');

        return $q->execute();
    }

}

